language: node_js
node_js:
- '0.11'
before_install: npm install -g grunt-cli selenium-standalone
install:
  - npm install
  - bower install
  - selenium-standalone install
before_script: selenium-standalone start &
script:
  - grunt test
